version: '3'

services:

  postgres:
    build: ./postgres
    volumes:
      - "/opt/teamcity/pg_data:/var/lib/postgresql/data"
      - "/opt/teamcity/pg_backup:/backups"
    env_file: .env
    restart: always

  server:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    hostname: ${VIRTUAL_HOST}
    volumes:
      - "/opt/teamcity/data:/data/teamcity_server/datadir"
      - "/opt/teamcity/logs:/opt/teamcity/logs"
    ports:
      - 8111:8111
    depends_on:
      - postgres
    env_file: .env
    restart: always

  nginx:
    image: nginx
    links:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/tc.conf:/etc/nginx/conf.d/default.conf"
    env_file: .env
