version: '3'

services:
  postgres:
    container_name: postgres
    build: ./postgres
    volumes:
      - "/postgres/data:/var/lib/postgresql/data"
      - "/postgres/backup:/backups"
    env_file: .env
    restart: always

  server:
    container_name: teamcity-server
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    hostname: ${VIRTUAL_HOST}
    volumes:
      - "/teamcity/data:/data/teamcity_server/datadir"
      - "/teamcity/logs:/opt/teamcity/logs"
    ports:
      - 8111:8111
    depends_on:
      - postgres
    env_file: .env
    restart: always

  nginx:
    container_name: proxy-server
    image: nginx
    links:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/teamcity.conf:/etc/nginx/conf.d/teamcity.conf"
    env_file: .env
    restart: always
